---
title: "MA DMF Middle Ground"
author: "Randall Hughes"
date: "10/12/2017"
output:
  pdf_document: default
  html_document: default
---

#Randall test

#Packages
```{r}
#library(dplyr)
#library(sciplot)
```


#Importing Data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
mg <- read.csv("MG_restoration_data.csv", header=T)
mg$no.sites <- as.factor(mg$no.sites)
str(mg)

```

#Spring 2017 PLANTING 1 Month Monitoring Analyses
```{r}
#Data organization
mg.spring2017.1month <- filter(mg, mg$planting.date == "Spring" & mg$sample.point == "1month")
str(mg.spring2017.1month)
```

##Shoot density
```{r}
#Data management- excluding plot with no discs remaining
mg.spring2017.1month.den <- subset(mg.spring2017.1month, no.discs > 0)

#Model 1
model = lm(no.shoots ~ diversity.treatment + identity + no.discs + transect, data = mg.spring2017.1month.den)
anova(model) #diversity, identity, no.discs --> significant
plot(shoots.per.disc ~ diversity.treatment, data = mg.spring2017.1month.den)
plot(shoots.per.disc ~ identity, data = mg.spring2017.1month.den)

#Model 2: diversity (parsed between 3 and 5); number of discs as covariate; transect removed
model = lm(no.shoots ~ no.sites + identity + no.discs, data=mg.spring2017.1month.den)
anova(model) #identity, no.discs, diversity --> significant
plot(shoots.per.disc ~ no.sites, data = mg.spring2017.1month.den)

#Model3: differences between mean mono and mean poly for poly 3 and poly 5 looking for overyielding
##5poly
###Data management
mg.spring2017.1month.den.Poly5 <- filter(mg.spring2017.1month.den, no.sites != "3")

###model
model.5poly = lm(no.shoots ~ no.sites + identity + no.discs, data=mg.spring2017.1month.den.Poly5)
anova(model.5poly) #no.discs, no.sites, identity --> significant; mono > poly
plot(shoots.per.disc ~ no.sites, data = mg.spring2017.1month.den.Poly5)

##3poly
###Data management
mg.spring2017.1month.den.Poly3 <- subset(mg.spring2017.1month.den, identity == "Niles" | identity == "Poly 3" | identity == "West" | identity == "Lynn" )

###model
model.3poly = lm(no.shoots ~ no.sites + identity + no.discs, data=mg.spring2017.1month.den.Poly3)
anova(model.3poly) #no.discs, no.sites, and identity --> significant, no overyielding
plot(shoots.per.disc ~ identity, data = mg.spring2017.1month.den.Poly3, ylim = c(0,15))
plot(shoots.per.disc ~ no.sites, data = mg.spring2017.1month.den.Poly3, ylim = c(0,15))
```

##Percent cover
```{r}
#Percent cover - differences by transect; number of discs as covariate
model = lm(percent.cover ~ diversity.treatment + identity + no.discs + transect , data = mg.spring2017.1month)
anova(model)

#percent cover - differences by diversity (parsed between 3 and 5), identity; number of discs as covariate; transect removed
model = lm(percent.cover ~ no.sites + identity + no.discs, data = mg.spring2017.1month)
anova(model) #why is identity excluded from output?       ##########???################
```

##Canopy height
```{r}
#Data management: removing data points with canopy height of 0
mg.spring2017.1month.ch <- subset(mg.spring2017.1month, canopy.height > 0)

#Model 1: by diversity and identity; number of discs as covariate (but not sure why it matters?)
model = lm(canopy.height ~ diversity.treatment + identity + no.discs + transect , data = mg.spring2017.1month.ch)
anova(model) #diversity, identity --> significant; no.discs --> marginal significance
plot(canopy.height ~ diversity.treatment, data = mg.spring2017.1month.ch)
plot(canopy.height ~ identity, data = mg.spring2017.1month.ch)
plot(canopy.height ~ no.discs, data = mg.spring2017.1month.ch)

#Model 2: diversity (parsed between 3 and 5); transect removed
model = lm(canopy.height ~ no.sites + identity + no.discs, data = mg.spring2017.1month.ch)
anova(model) #identity, diversity --> significant; no.discs --> marginally significant
plot(canopy.height ~ no.sites, data = mg.spring2017.1month.ch)

#Model3: differences between mean mono and mean poly for poly 3 and poly 5 looking for overyielding
##5poly
###Data management
mg.spring2017.1month.ch.Poly5 <- filter(mg.spring2017.1month.ch, no.sites != "3")

###model
model.5poly = lm(canopy.height ~ no.sites + identity + no.discs, data=mg.spring2017.1month.ch.Poly5)
anova(model.5poly) #no.sites, identity, no discs --> significant; overyielding, not transgressive overyielding
plot(canopy.height ~ no.sites, data = mg.spring2017.1month.ch.Poly5)
plot(canopy.height ~ identity, data = mg.spring2017.1month.ch.Poly5)

##3poly
###Data management
mg.spring2017.1month.ch.Poly3 <- subset(mg.spring2017.1month.ch, identity == "Niles" | identity == "Poly 3" | identity == "West" | identity == "Lynn" )

###model
model.3poly = lm(canopy.height ~ no.sites + identity + no.discs, data=mg.spring2017.1month.ch.Poly3)
anova(model.3poly) # identity and no.sites --> significant; no overyielding
plot(canopy.height ~ no.sites, data = mg.spring2017.1month.ch.Poly3)
plot(canopy.height ~ identity, data = mg.spring2017.1month.den.Poly3)
```

#****************************************************************************************************************************

#FALL 2017 PLANTING 1 Month Monitoring Analyses
```{r}
#Data organization
mg.fall2017.1month <- filter(mg, planting.date == "Fall" & sample.point == "1month")
mg.fall2017.1month$no.sites <- as.factor(mg.fall2017.1month$no.sites)
str(mg.fall2017.1month)
```

##Shoot density
```{r}
#Data management- excluding plot with no discs remaining
mg.fall2017.1month.den <- subset(mg.fall2017.1month, no.discs > 0)

#Model 1
model = lm(no.shoots ~ diversity.treatment + identity + no.discs + transect, data = mg.fall2017.1month.den)
anova(model) #identity, no.discs --> significant
plot(shoots.per.disc ~ diversity.treatment, data = mg.fall2017.1month.den)
plot(shoots.per.disc ~ identity, data = mg.fall2017.1month.den)

#Model 2: diversity (parsed between 3 and 5); number of discs as covariate; transect removed
model = lm(no.shoots ~ no.sites + identity + no.discs, data=mg.fall2017.1month.den)
anova(model) #identity, no.discs --> significant;
plot(shoots.per.disc ~ no.sites, data = mg.fall2017.1month.den)

#Model3: differences between mean mono and mean poly for poly 3 and poly 5 looking for overyielding
##5poly
###Data management
mg.fall2017.1month.den.Poly5 <- filter(mg.fall2017.1month.den, no.sites != "3")

###model
model.5poly = lm(no.shoots ~ no.sites + identity + no.discs, data=mg.fall2017.1month.den.Poly5)
anova(model.5poly) #no.discs, identity --> significant; no overyielding

##3poly
###Data management
mg.fall2017.1month.den.Poly3 <- subset(mg.fall2017.1month.den, identity == "Niles" | identity == "Poly 3" | identity == "West" | identity == "Nahant" )

###model
model.3poly = lm(no.shoots ~ no.sites + identity + no.discs, data=mg.fall2017.1month.den.Poly3)
anova(model.3poly) #no.discs and no.sites(diversity) --> significant, overyielding, but not transgressive overyielding
plot(shoots.per.disc ~ no.sites, data = mg.fall2017.1month.den.Poly3, ylim = c(0,15))
plot(shoots.per.disc ~ identity, data = mg.fall2017.1month.den.Poly3, ylim = c(0,15))
```

##Percent cover
```{r}
#Percent cover - differences by transect; number of discs as covariate
model = lm(percent.cover ~ diversity.treatment + identity + no.discs + transect , data = mg.fall2017.1month)
anova(model)
plot(percent.cover ~ transect, data = mg.fall2017.1month)

#percent cover - differences by diversity (parsed between 3 and 5), identity; number of discs as covariate; transect removed
model = lm(percent.cover ~ no.sites + identity + no.discs, data = mg.fall2017.1month)
anova(model)
```

##Canopy height
```{r}
#Data management: removing data points with canopy height of 0
mg.fall2017.1month.ch <- subset(mg.fall2017.1month, canopy.height > 0)

#Model 1: by diversity and identity; number of discs as covariate (but not sure why it matters?)
model = lm(canopy.height ~ diversity.treatment + identity + no.discs + transect , data = mg.fall2017.1month.ch)
anova(model) #diversity, identity --> significant; transect --> marginal significance
plot(canopy.height ~ diversity.treatment, data = mg.fall2017.1month.ch)
plot(canopy.height ~ identity, data = mg.fall2017.1month.ch)

#Model 2: diversity (parsed between 3 and 5); transect removed
model = lm(canopy.height ~ no.sites + identity + no.discs, data = mg.fall2017.1month.ch)
anova(model) #identity, diversity --> significant
plot(canopy.height ~ no.sites, data = mg.fall2017.1month.ch)

#Model3: differences between mean mono and mean poly for poly 3 and poly 5 looking for overyielding
##5poly
###Data management
mg.fall2017.1month.ch.Poly5 <- filter(mg.fall2017.1month.ch, no.sites != "3")

###model
model.5poly = lm(canopy.height ~ no.sites + identity + no.discs, data=mg.fall2017.1month.ch.Poly5)
anova(model.5poly) #no.sites, identity --> significant, overyielding, not transgressive overyielding
plot(canopy.height ~ no.sites, data = mg.fall2017.1month.ch.Poly5)
plot(canopy.height ~ identity, data = mg.fall2017.1month.ch.Poly5)

##3poly
###Data management
mg.fall2017.1month.ch.Poly3 <- subset(mg.fall2017.1month.ch, identity == "Niles" | identity == "Poly 3" | identity == "West" | identity == "Nahant" )

###model
model.3poly = lm(canopy.height ~ no.sites + identity + no.discs, data=mg.fall2017.1month.ch.Poly3)
anova(model.3poly) #identity --> marginally significant, no overyielding
plot(canopy.height ~ no.sites, data = mg.fall2017.1month.ch.Poly3)
plot(canopy.height ~ identity, data = mg.fall2017.1month.den.Poly3)
```

#****************************************************************************************************************************

#Restoration success: mean discs per plot
```{r}
#Model
model = lm(no.discs ~ no.sites + identity + planting.date + transect:planting.date + no.sites:planting.date + identity:planting.date, data = mg)
anova(model) # transect:planting.date and no.sites:planting.date --> significant

bargraph.CI(x.factor = planting.date, response = no.discs, group = no.sites, data = mg, legend = T, x.leg = 7, y.leg =6, ylim = c(0,6)) #spring poly5s had fewer discs remaining after 1 month
bargraph.CI(x.factor = planting.date, response = no.discs, group = transect, data = mg, legend = T, x.leg = 5.7, y.leg =6, ylim = c(0,6)) #south transect in the fall had fewer discs remaining after 1 month
```




